name: 'Check Tags in Airflow DAG'
description: 'Check Tags in Airflow DAG in GitHub repo'

author: 'Dauren Altayev'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies     
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash      
    - name: Run script
      run: python ${{ github.action_path }}/src/check-airflow-dags-tags.py
      shell: bash
      