name: 'Check Tags in Airflow DAG'
description: 'Check Tags in Airflow DAG in GitHub repo'

inputs:
  directory:
    description: 'Specify path to Airflow DAG directory'
    required: true
    default: "orchestration/dags"
  emr_tags:
    description: 'List of required EMR Tags'
    required: true
    default: '[{"key": "ssmmanaged", "value": "no see CSRC_DBC_933_EC2_SSM_MANAGED"}, {"key": "CSRC_DBC_933", "value": "CSRC_DBC_933_EC2_SSM_MANAGED"}]'
      
author: 'Dauren Altayev'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies     
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
        echo "EMR_TAGS=${{ toJson(inputs.emr_tags) }}" >> $GITHUB_ENV
      shell: bash            
    - name: Run script
      run: python ${{ github.action_path }}/src/check-airflow-dags-tags.py        
      shell: bash
      