name: 'Check Tags in Airflow DAG'
description: 'Check Tags in Airflow DAG in GitHub repo'
inputs:
  directory:
    description: 'Specify path to Airflow DAG directory'
    required: true
    default: "orchestration/dags"
  emr_tags:
    description: 'List of required EMR Tags'
    required: true
#    default: |
#      "[{\"Key\": \"ssmmanaged\", \"Value\": \"no see CSRC_DBC_933_EC2_SSM_MANAGED\"},{\"Key\": \"CSRC_DBC_933\", \"Value\": \"CSRC_DBC_933_EC2_SSM_MANAGED\"}]"
    default: |
      [
        {"Key": "ssmmanaged", "Value": "no see CSRC_DBC_933_EC2_SSM_MANAGED"},
        {"Key": "CSRC_DBC_933", "Value": "CSRC_DBC_933_EC2_SSM_MANAGED"}
      ]
      
author: 'Dauren Altayev'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies    
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
        echo 'export EMR_TAGS='$(echo $EMR_TAGS) > inputsemrtags.txt
      shell: bash            
    - name: Run script
      run: python ${{ github.action_path }}/src/check-airflow-dags-tags.py        
      shell: bash